### ISSUE TITLE
intereses futuros

### ISSUE THREAD

**Issue by ccarruitero** [mozillaperu/participacion#7]
Creo que seria bueno preguntar también acerca de tecnologías que desean aprender o explorar más a fondo el próximo año.  Tal vez que sea solo una pregunta abierta, aunque no se que tanto complicaria esto la tabulación de los resultados?

**Comment by AngelFQC** [comment]
Las preguntas abiertas son difíciles de tratar en las encuestas... habría que revisar una por una también.

**Comment by ccarruitero** [comment]
en ese caso podriamos dejarlo para más adelante en todo caso.
